// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: improvement.proto

package loadgrpc.flowcontrol;

public interface FlowControlResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:loadgrpc.FlowControlResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 request = 10;</code>
   * @return The request.
   */
  int getRequest();
}
