// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: improvement.proto

package loadgrpc.flowcontrol;

public final class Improvement {
  private Improvement() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_loadgrpc_FlowControlledMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_loadgrpc_FlowControlledMsg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_loadgrpc_FlowControlResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_loadgrpc_FlowControlResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021improvement.proto\022\010loadgrpc\">\n\021FlowCon" +
      "trolledMsg\022\026\n\016senderHostname\030\n \001(\t\022\021\n\tre" +
      "questId\030\024 \001(\t\"&\n\023FlowControlResponse\022\017\n\007" +
      "request\030\n \001(\r2m\n\022FlowControlService\022W\n\023C" +
      "ontrolledStreaming\022\033.loadgrpc.FlowContro" +
      "lledMsg\032\035.loadgrpc.FlowControlResponse\"\000" +
      "(\0010\001B\030\n\024loadgrpc.flowcontrolP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_loadgrpc_FlowControlledMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_loadgrpc_FlowControlledMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_loadgrpc_FlowControlledMsg_descriptor,
        new java.lang.String[] { "SenderHostname", "RequestId", });
    internal_static_loadgrpc_FlowControlResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_loadgrpc_FlowControlResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_loadgrpc_FlowControlResponse_descriptor,
        new java.lang.String[] { "Request", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
