// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

package loadgrpc.example;

public final class Example {
  private Example() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_loadgrpc_ExampleMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_loadgrpc_ExampleMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_loadgrpc_ExampleResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_loadgrpc_ExampleResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rexample.proto\022\010loadgrpc\"!\n\016ExampleMess" +
      "age\022\017\n\007payload\030\n \001(\t\"\"\n\017ExampleResponse\022" +
      "\017\n\007payload\030\n \001(\t2\275\002\n\016ExampleService\022>\n\005U" +
      "nary\022\030.loadgrpc.ExampleMessage\032\031.loadgrp" +
      "c.ExampleResponse\"\000\022J\n\017ClientStreaming\022\030" +
      ".loadgrpc.ExampleMessage\032\031.loadgrpc.Exam" +
      "pleResponse\"\000(\001\022J\n\017ServerStreaming\022\030.loa" +
      "dgrpc.ExampleMessage\032\031.loadgrpc.ExampleR" +
      "esponse\"\0000\001\022S\n\026BidirectionalStreaming\022\030." +
      "loadgrpc.ExampleMessage\032\031.loadgrpc.Examp" +
      "leResponse\"\000(\0010\001B\024\n\020loadgrpc.exampleP\001b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_loadgrpc_ExampleMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_loadgrpc_ExampleMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_loadgrpc_ExampleMessage_descriptor,
        new java.lang.String[] { "Payload", });
    internal_static_loadgrpc_ExampleResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_loadgrpc_ExampleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_loadgrpc_ExampleResponse_descriptor,
        new java.lang.String[] { "Payload", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
