// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

package loadgrpc.example;

public interface ExampleResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:loadgrpc.ExampleResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string payload = 10;</code>
   * @return The payload.
   */
  java.lang.String getPayload();
  /**
   * <code>string payload = 10;</code>
   * @return The bytes for payload.
   */
  com.google.protobuf.ByteString
      getPayloadBytes();
}
